### PR TITLE
Jake's changes

### PR DESCRIPTION
**Pull request by jakebloom**
I have added a paragraph that I feel will increase your employability.

### CODE REVIEW

**Comment by jakebloom** [comment]
This pull request looks good, I suggest you integrate the changes

**Comment by nickw444** [comment]
Looks good, except you haven't submitted test cases. Please read the CONTRIBUTING.md file for details on how to contribute to this project :)

**Comment by nickw444** [comment]
+1 though

**Comment by jakebloom** [comment]
Fuck you man this patch is solid

**Pull request closed without merging**
